on: pull_request
name: Pull request automation

jobs:
  pull-request-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/pull-request-automation
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
